import { OBJECTIVES } from '../i18n';
import { Objective, ObjectiveType, GameExpansion, GamePhase } from './types';

export const Objectives : Array<Objective> = [
  // Public 1

  //// Basic
  {
    name: OBJECTIVES.CORNER_THE_MARKET.TITLE,
    condition: OBJECTIVES.CORNER_THE_MARKET.CONDITION,
    points: 1,
    description: OBJECTIVES.CORNER_THE_MARKET.DESCRIPTION,
    type: ObjectiveType.Public1,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.DEVELOP_WEAPONRY.TITLE,
    condition: OBJECTIVES.DEVELOP_WEAPONRY.CONDITION,
    points: 1,
    description: OBJECTIVES.DEVELOP_WEAPONRY.DESCRIPTION,
    type: ObjectiveType.Public1,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.DIVERSIFY_RESEARCH.TITLE,
    condition: OBJECTIVES.DIVERSIFY_RESEARCH.CONDITION,
    points: 1,
    description: OBJECTIVES.DIVERSIFY_RESEARCH.DESCRIPTION,
    type: ObjectiveType.Public1,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.ERECT_A_MONUMENT.TITLE,
    condition: OBJECTIVES.ERECT_A_MONUMENT.CONDITION,
    points: 1,
    description: OBJECTIVES.ERECT_A_MONUMENT.DESCRIPTION,
    type: ObjectiveType.Public1,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.EXPAND_BORDERS.TITLE,
    condition: OBJECTIVES.EXPAND_BORDERS.CONDITION,
    points: 1,
    description: OBJECTIVES.EXPAND_BORDERS.DESCRIPTION,
    type: ObjectiveType.Public1,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.FOUND_RESEARCH_OUTPOST.TITLE,
    condition: OBJECTIVES.FOUND_RESEARCH_OUTPOST.CONDITION,
    points: 1,
    description: OBJECTIVES.FOUND_RESEARCH_OUTPOST.DESCRIPTION,
    type: ObjectiveType.Public1,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.INTIMIDATE_COUNCIL.TITLE,
    condition: OBJECTIVES.INTIMIDATE_COUNCIL.CONDITION,
    points: 1,
    description: OBJECTIVES.INTIMIDATE_COUNCIL.DESCRIPTION,
    type: ObjectiveType.Public1,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.LEAD_FROM_THE_FRONT.TITLE,
    condition: OBJECTIVES.LEAD_FROM_THE_FRONT.CONDITION,
    points: 1,
    description: OBJECTIVES.LEAD_FROM_THE_FRONT.DESCRIPTION,
    type: ObjectiveType.Public1,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.NEGOTIATE_TRADE_ROUTES.TITLE,
    condition: OBJECTIVES.NEGOTIATE_TRADE_ROUTES.CONDITION,
    points: 1,
    description: OBJECTIVES.NEGOTIATE_TRADE_ROUTES.DESCRIPTION,
    type: ObjectiveType.Public1,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.SWAY_THE_COUNCIL.TITLE,
    condition: OBJECTIVES.SWAY_THE_COUNCIL.CONDITION,
    points: 1,
    description: OBJECTIVES.SWAY_THE_COUNCIL.DESCRIPTION,
    type: ObjectiveType.Public1,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Status,
  },
  //// PoK
  {
    name: OBJECTIVES.AMASS_WEALTH.TITLE,
    condition: OBJECTIVES.AMASS_WEALTH.CONDITION,
    points: 1,
    description: OBJECTIVES.AMASS_WEALTH.DESCRIPTION,
    type: ObjectiveType.Public1,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.BUILD_DEFENCES.TITLE,
    condition: OBJECTIVES.BUILD_DEFENCES.CONDITION,
    points: 1,
    description: OBJECTIVES.BUILD_DEFENCES.DESCRIPTION,
    type: ObjectiveType.Public1,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.DISCOVER_LOST_OUTPOST.TITLE,
    condition: OBJECTIVES.DISCOVER_LOST_OUTPOST.CONDITION,
    points: 1,
    description: OBJECTIVES.DISCOVER_LOST_OUTPOST.DESCRIPTION,
    type: ObjectiveType.Public1,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.ENGINEER_A_MARVEL.TITLE,
    condition: OBJECTIVES.ENGINEER_A_MARVEL.CONDITION,
    points: 1,
    description: OBJECTIVES.ENGINEER_A_MARVEL.DESCRIPTION,
    type: ObjectiveType.Public1,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.EXPLORE_DEEP_SPACE.TITLE,
    condition: OBJECTIVES.EXPLORE_DEEP_SPACE.CONDITION,
    points: 1,
    description: OBJECTIVES.EXPLORE_DEEP_SPACE.DESCRIPTION,
    type: ObjectiveType.Public1,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.IMPROVE_INFRASTRUCTURE.TITLE,
    condition: OBJECTIVES.IMPROVE_INFRASTRUCTURE.CONDITION,
    points: 1,
    description: OBJECTIVES.IMPROVE_INFRASTRUCTURE.DESCRIPTION,
    type: ObjectiveType.Public1,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.MAKE_HISTORY.TITLE,
    condition: OBJECTIVES.MAKE_HISTORY.CONDITION,
    points: 1,
    description: OBJECTIVES.MAKE_HISTORY.DESCRIPTION,
    type: ObjectiveType.Public1,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.POPULATE_THE_OUTER_RIM.TITLE,
    condition: OBJECTIVES.POPULATE_THE_OUTER_RIM.CONDITION,
    points: 1,
    description: OBJECTIVES.POPULATE_THE_OUTER_RIM.DESCRIPTION,
    type: ObjectiveType.Public1,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.PUSH_BOUNDARIES.TITLE,
    condition: OBJECTIVES.PUSH_BOUNDARIES.CONDITION,
    points: 1,
    description: OBJECTIVES.PUSH_BOUNDARIES.DESCRIPTION,
    type: ObjectiveType.Public1,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.RAISE_A_FLEET.TITLE,
    condition: OBJECTIVES.RAISE_A_FLEET.CONDITION,
    points: 1,
    description: OBJECTIVES.RAISE_A_FLEET.DESCRIPTION,
    type: ObjectiveType.Public1,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Status,
  },
  // Public 2
  //// Basic
  {
    name: OBJECTIVES.CENTRALIZE_GALACTIC_TRADE.TITLE,
    condition: OBJECTIVES.CENTRALIZE_GALACTIC_TRADE.CONDITION,
    points: 2,
    description: OBJECTIVES.CENTRALIZE_GALACTIC_TRADE.DESCRIPTION,
    type: ObjectiveType.Public2,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.CONQUER_THE_WEAK.TITLE,
    condition: OBJECTIVES.CONQUER_THE_WEAK.CONDITION,
    points: 2,
    description: OBJECTIVES.CONQUER_THE_WEAK.DESCRIPTION,
    type: ObjectiveType.Public2,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.FORM_GALACTIC_BRAIN_TRUST.TITLE,
    condition: OBJECTIVES.FORM_GALACTIC_BRAIN_TRUST.CONDITION,
    points: 2,
    description: OBJECTIVES.FORM_GALACTIC_BRAIN_TRUST.DESCRIPTION,
    type: ObjectiveType.Public2,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.FOUND_A_GOLDEN_AGE.TITLE,
    condition: OBJECTIVES.FOUND_A_GOLDEN_AGE.CONDITION,
    points: 2,
    description: OBJECTIVES.FOUND_A_GOLDEN_AGE.DESCRIPTION,
    type: ObjectiveType.Public2,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.GALVANIZE_THE_PEOPLE.TITLE,
    condition: OBJECTIVES.GALVANIZE_THE_PEOPLE.CONDITION,
    points: 2,
    description: OBJECTIVES.GALVANIZE_THE_PEOPLE.DESCRIPTION,
    type: ObjectiveType.Public2,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.MANIPULATE_GALACTIC_LAW.TITLE,
    condition: OBJECTIVES.MANIPULATE_GALACTIC_LAW.CONDITION,
    points: 2,
    description: OBJECTIVES.MANIPULATE_GALACTIC_LAW.DESCRIPTION,
    type: ObjectiveType.Public2,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.MASTER_THE_SCIENCE.TITLE,
    condition: OBJECTIVES.MASTER_THE_SCIENCE.CONDITION,
    points: 2,
    description: OBJECTIVES.MASTER_THE_SCIENCE.DESCRIPTION,
    type: ObjectiveType.Public2,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.REVOLUTIONIZE_WARFARE.TITLE,
    condition: OBJECTIVES.REVOLUTIONIZE_WARFARE.CONDITION,
    points: 2,
    description: OBJECTIVES.REVOLUTIONIZE_WARFARE.DESCRIPTION,
    type: ObjectiveType.Public2,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.SUBDUE_THE_GALAXY.TITLE,
    condition: OBJECTIVES.SUBDUE_THE_GALAXY.CONDITION,
    points: 2,
    description: OBJECTIVES.SUBDUE_THE_GALAXY.DESCRIPTION,
    type: ObjectiveType.Public2,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.UNIFY_THE_COLONIES.TITLE,
    condition: OBJECTIVES.UNIFY_THE_COLONIES.CONDITION,
    points: 2,
    description: OBJECTIVES.UNIFY_THE_COLONIES.DESCRIPTION,
    type: ObjectiveType.Public2,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Status,
  },
  //// PoK
  {
    name: OBJECTIVES.ACHIEVE_SUPREMACY.TITLE,
    condition: OBJECTIVES.ACHIEVE_SUPREMACY.CONDITION,
    points: 2,
    description: OBJECTIVES.ACHIEVE_SUPREMACY.DESCRIPTION,
    type: ObjectiveType.Public2,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.BECOME_A_LEGEND.TITLE,
    condition: OBJECTIVES.BECOME_A_LEGEND.CONDITION,
    points: 2,
    description: OBJECTIVES.BECOME_A_LEGEND.DESCRIPTION,
    type: ObjectiveType.Public2,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.COMMAND_AN_ARMADA.TITLE,
    condition: OBJECTIVES.COMMAND_AN_ARMADA.CONDITION,
    points: 2,
    description: OBJECTIVES.COMMAND_AN_ARMADA.DESCRIPTION,
    type: ObjectiveType.Public2,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.CONSTRUCT_MASSIVE_CITIES.TITLE,
    condition: OBJECTIVES.CONSTRUCT_MASSIVE_CITIES.CONDITION,
    points: 2,
    description: OBJECTIVES.CONSTRUCT_MASSIVE_CITIES.DESCRIPTION,
    type: ObjectiveType.Public2,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.CONTROL_THE_BORDERLANDS.TITLE,
    condition: OBJECTIVES.CONTROL_THE_BORDERLANDS.CONDITION,
    points: 2,
    description: OBJECTIVES.CONTROL_THE_BORDERLANDS.DESCRIPTION,
    type: ObjectiveType.Public2,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.HOLD_VAST_RESERVES.TITLE,
    condition: OBJECTIVES.HOLD_VAST_RESERVES.CONDITION,
    points: 2,
    description: OBJECTIVES.HOLD_VAST_RESERVES.DESCRIPTION,
    type: ObjectiveType.Public2,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.PATROL_VAST_TERRITORIES.TITLE,
    condition: OBJECTIVES.PATROL_VAST_TERRITORIES.CONDITION,
    points: 2,
    description: OBJECTIVES.PATROL_VAST_TERRITORIES.DESCRIPTION,
    type: ObjectiveType.Public2,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.PROTECT_THE_BORDER.TITLE,
    condition: OBJECTIVES.PROTECT_THE_BORDER.CONDITION,
    points: 2,
    description: OBJECTIVES.PROTECT_THE_BORDER.DESCRIPTION,
    type: ObjectiveType.Public2,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.RECLAIM_ANCIENT_MONUMENTS.TITLE,
    condition: OBJECTIVES.RECLAIM_ANCIENT_MONUMENTS.CONDITION,
    points: 2,
    description: OBJECTIVES.RECLAIM_ANCIENT_MONUMENTS.DESCRIPTION,
    type: ObjectiveType.Public2,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.RULE_DISTANT_LANDS.TITLE,
    condition: OBJECTIVES.RULE_DISTANT_LANDS.CONDITION,
    points: 2,
    description: OBJECTIVES.RULE_DISTANT_LANDS.DESCRIPTION,
    type: ObjectiveType.Public2,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Status,
  },

  // Secrets
  //// Basic Action
  {
    name: OBJECTIVES.DESTROY_THEIR_GREATEST_SHIP.TITLE,
    condition: OBJECTIVES.DESTROY_THEIR_GREATEST_SHIP.CONDITION,
    points: 1,
    description: OBJECTIVES.DESTROY_THEIR_GREATEST_SHIP.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Action,
  },
  {
    name: OBJECTIVES.MAKE_AN_EXAMPLE_OF_THEIR_WORLD.TITLE,
    condition: OBJECTIVES.MAKE_AN_EXAMPLE_OF_THEIR_WORLD.CONDITION,
    points: 1,
    description: OBJECTIVES.MAKE_AN_EXAMPLE_OF_THEIR_WORLD.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Action,
  },
  {
    name: OBJECTIVES.SPARK_A_REBELLION.TITLE,
    condition: OBJECTIVES.SPARK_A_REBELLION.CONDITION,
    points: 1,
    description: OBJECTIVES.SPARK_A_REBELLION.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Action,
  },
  {
    name: OBJECTIVES.TURN_THEIR_FLEETS_TO_DUST.TITLE,
    condition: OBJECTIVES.TURN_THEIR_FLEETS_TO_DUST.CONDITION,
    points: 1,
    description: OBJECTIVES.TURN_THEIR_FLEETS_TO_DUST.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Action,
  },
  {
    name: OBJECTIVES.UNVEIL_FLAGSHIP.TITLE,
    condition: OBJECTIVES.UNVEIL_FLAGSHIP.CONDITION,
    points: 1,
    description: OBJECTIVES.UNVEIL_FLAGSHIP.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Action,
  },
  //// PoK Action
  {
    name: OBJECTIVES.BECOME_A_MARTYR.TITLE,
    condition: OBJECTIVES.BECOME_A_MARTYR.CONDITION,
    points: 1,
    description: OBJECTIVES.BECOME_A_MARTYR.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Action,
  },
  {
    name: OBJECTIVES.BETRAY_A_FRIEND.TITLE,
    condition: OBJECTIVES.BETRAY_A_FRIEND.CONDITION,
    points: 1,
    description: OBJECTIVES.BETRAY_A_FRIEND.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Action,
  },
  {
    name: OBJECTIVES.BRAVE_THE_VOID.TITLE,
    condition: OBJECTIVES.BRAVE_THE_VOID.CONDITION,
    points: 1,
    description: OBJECTIVES.BRAVE_THE_VOID.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Action,
  },
  {
    name: OBJECTIVES.DARKEN_THE_SKIES.TITLE,
    condition: OBJECTIVES.DARKEN_THE_SKIES.CONDITION,
    points: 1,
    description: OBJECTIVES.DARKEN_THE_SKIES.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Action,
  },
  {
    name: OBJECTIVES.DEMONSTRATE_YOUR_POWER.TITLE,
    condition: OBJECTIVES.DEMONSTRATE_YOUR_POWER.CONDITION,
    points: 1,
    description: OBJECTIVES.DEMONSTRATE_YOUR_POWER.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Action,
  },
  {
    name: OBJECTIVES.FIGHT_WITH_PRECISION.TITLE,
    condition: OBJECTIVES.FIGHT_WITH_PRECISION.CONDITION,
    points: 1,
    description: OBJECTIVES.FIGHT_WITH_PRECISION.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Action,
  },
  {
    name: OBJECTIVES.PROVE_ENDURANCE.TITLE,
    condition: OBJECTIVES.PROVE_ENDURANCE.CONDITION,
    points: 1,
    description: OBJECTIVES.PROVE_ENDURANCE.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Action,
  },
  //// Basic Status
  {
    name: OBJECTIVES.ADAPT_NEW_STRATEGIES.TITLE,
    condition: OBJECTIVES.ADAPT_NEW_STRATEGIES.CONDITION,
    points: 1,
    description: OBJECTIVES.ADAPT_NEW_STRATEGIES.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.BECOME_THE_GATEKEEPER.TITLE,
    condition: OBJECTIVES.BECOME_THE_GATEKEEPER.CONDITION,
    points: 1,
    description: OBJECTIVES.BECOME_THE_GATEKEEPER.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.CONTROL_THE_REGION.TITLE,
    condition: OBJECTIVES.CONTROL_THE_REGION.CONDITION,
    points: 1,
    description: OBJECTIVES.CONTROL_THE_REGION.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.CUT_SUPPLY_LINES.TITLE,
    condition: OBJECTIVES.CUT_SUPPLY_LINES.CONDITION,
    points: 1,
    description: OBJECTIVES.CUT_SUPPLY_LINES.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.ESTABLISH_A_PERIMETER.TITLE,
    condition: OBJECTIVES.ESTABLISH_A_PERIMETER.CONDITION,
    points: 1,
    description: OBJECTIVES.ESTABLISH_A_PERIMETER.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.FORGE_AN_ALLIANCE.TITLE,
    condition: OBJECTIVES.FORGE_AN_ALLIANCE.CONDITION,
    points: 1,
    description: OBJECTIVES.FORGE_AN_ALLIANCE.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.FORM_A_SPY_NETWORK.TITLE,
    condition: OBJECTIVES.FORM_A_SPY_NETWORK.CONDITION,
    points: 1,
    description: OBJECTIVES.FORM_A_SPY_NETWORK.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.FUEL_THE_WAR_MACHINE.TITLE,
    condition: OBJECTIVES.FUEL_THE_WAR_MACHINE.CONDITION,
    points: 1,
    description: OBJECTIVES.FUEL_THE_WAR_MACHINE.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.GATHER_A_MIGHTY_FLEET.TITLE,
    condition: OBJECTIVES.GATHER_A_MIGHTY_FLEET.CONDITION,
    points: 1,
    description: OBJECTIVES.GATHER_A_MIGHTY_FLEET.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.LEARN_THE_SECRETS_OF_THE_COSMOS.TITLE,
    condition: OBJECTIVES.LEARN_THE_SECRETS_OF_THE_COSMOS.CONDITION,
    points: 1,
    description: OBJECTIVES.LEARN_THE_SECRETS_OF_THE_COSMOS.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.MASTER_THE_LAWS_OF_PHYSICS.TITLE,
    condition: OBJECTIVES.MASTER_THE_LAWS_OF_PHYSICS.CONDITION,
    points: 1,
    description: OBJECTIVES.MASTER_THE_LAWS_OF_PHYSICS.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.MINE_RARE_METALS.TITLE,
    condition: OBJECTIVES.MINE_RARE_METALS.CONDITION,
    points: 1,
    description: OBJECTIVES.MINE_RARE_METALS.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.MONOPOLIZE_PRODUCTION.TITLE,
    condition: OBJECTIVES.MONOPOLIZE_PRODUCTION.CONDITION,
    points: 1,
    description: OBJECTIVES.MONOPOLIZE_PRODUCTION.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.OCCUPY_THE_SEAT_OF_THE_EMPIRE.TITLE,
    condition: OBJECTIVES.OCCUPY_THE_SEAT_OF_THE_EMPIRE.CONDITION,
    points: 1,
    description: OBJECTIVES.OCCUPY_THE_SEAT_OF_THE_EMPIRE.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.THREATEN_ENEMIES.TITLE,
    condition: OBJECTIVES.THREATEN_ENEMIES.CONDITION,
    points: 1,
    description: OBJECTIVES.THREATEN_ENEMIES.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.Basic,
    phase: GamePhase.Status,
  },
  //// POK Status
  {
    name: OBJECTIVES.DEFY_SPACE_AND_TIME.TITLE,
    condition: OBJECTIVES.DEFY_SPACE_AND_TIME.CONDITION,
    points: 1,
    description: OBJECTIVES.DEFY_SPACE_AND_TIME.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.DESTROY_HERETICAL_WORKS.TITLE,
    condition: OBJECTIVES.DESTROY_HERETICAL_WORKS.CONDITION,
    points: 1,
    description: OBJECTIVES.DESTROY_HERETICAL_WORKS.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.ESTABLISH_HEGEMONY.TITLE,
    condition: OBJECTIVES.ESTABLISH_HEGEMONY.CONDITION,
    points: 1,
    description: OBJECTIVES.ESTABLISH_HEGEMONY.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.FOSTER_COHESION.TITLE,
    condition: OBJECTIVES.FOSTER_COHESION.CONDITION,
    points: 1,
    description: OBJECTIVES.FOSTER_COHESION.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.HOARD_RAW_MATERIALS.TITLE,
    condition: OBJECTIVES.HOARD_RAW_MATERIALS.CONDITION,
    points: 1,
    description: OBJECTIVES.HOARD_RAW_MATERIALS.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.MECHANIZE_THE_MILITARY.TITLE,
    condition: OBJECTIVES.MECHANIZE_THE_MILITARY.CONDITION,
    points: 1,
    description: OBJECTIVES.MECHANIZE_THE_MILITARY.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.OCCUPY_THE_FRINGE.TITLE,
    condition: OBJECTIVES.OCCUPY_THE_FRINGE.CONDITION,
    points: 1,
    description: OBJECTIVES.OCCUPY_THE_FRINGE.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.PRODUCE_EN_MASSE.TITLE,
    condition: OBJECTIVES.PRODUCE_EN_MASSE.CONDITION,
    points: 1,
    description: OBJECTIVES.PRODUCE_EN_MASSE.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.SEIZE_AN_ICON.TITLE,
    condition: OBJECTIVES.SEIZE_AN_ICON.CONDITION,
    points: 1,
    description: OBJECTIVES.SEIZE_AN_ICON.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.STAKE_YOUR_CLAIM.TITLE,
    condition: OBJECTIVES.STAKE_YOUR_CLAIM.CONDITION,
    points: 1,
    description: OBJECTIVES.STAKE_YOUR_CLAIM.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Status,
  },
  {
    name: OBJECTIVES.STRENGTHEN_BONDS.TITLE,
    condition: OBJECTIVES.STRENGTHEN_BONDS.CONDITION,
    points: 1,
    description: OBJECTIVES.STRENGTHEN_BONDS.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Status,
  },
  //// POK Agenda
  {
    name: OBJECTIVES.DICTATE_POLICY.TITLE,
    condition: OBJECTIVES.DICTATE_POLICY.CONDITION,
    points: 1,
    description: OBJECTIVES.DICTATE_POLICY.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Agenda,
  },
  {
    name: OBJECTIVES.DRIVE_THE_DEBATE.TITLE,
    condition: OBJECTIVES.DRIVE_THE_DEBATE.CONDITION,
    points: 1,
    description: OBJECTIVES.DRIVE_THE_DEBATE.DESCRIPTION,
    type: ObjectiveType.Secret,
    expansion: GameExpansion.ProphecyOfKings,
    phase: GamePhase.Agenda,
  },
];
