name: Push image
on:
  release:
    types: [published]
jobs:
  Explore-GitHub-Actions:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - run: echo "Releasing ${{ github.event.release.tag_name }}"

      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Yarn install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Yarn build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build

      - name: Log in to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_KEY }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: 587769564784/scorer:latest,587769564784/scorer:${{ github.event.release.tag_name }}
